// Atlas OS — HUD Data-Parts reconciliation (RFC 04 §6 / RFC 24,
// sub-fase 2.1, G13).
//
// The HUD WebSocket pushes streaming model output to the webview
// faster than the WebSocket can repaint. When a new chunk arrives for
// an in-flight turn the HUD wants to **update the in-place part**
// (append to the same card) rather than render a new card. The Vercel
// AI SDK pattern (vercel/ai, MIT) models this as `DataParts`: opaque
// key-value entries keyed by a stable string id; a part with the same
// id updates in place, a fresh id creates a new entry.
//
// The reconciliation layer here carries that pattern across the
// orchestrator's cascade failover: when a request is re-dispatched
// to a fallback model mid-stream, the journal must NOT persist the
// primary's partial frames as if they were final (they would
// overwrite the fallback's full output in the audit trail). We mark
// partial frames as **transient** and let `DataPartBuffer::keep` drop
// them at the end of the cascade; only **persistent** parts
// (tool-call deltas already-attached to the journal, plan deltas,
// commit messages written to disk) survive.
//
// The buffer is intentionally local to the orchestrator's request
// loop — it's not the HUD's own store (the HUD owns its Svelte
// writable). It's a labels-only ledger the orchestrator sends over
// the WS bus so the HUD can drive its reconciliation. See
// `core/bus.rs::BusEventKind::AgentDiff` for the existing wire-level
// event surface.

use std::collections::HashMap;

use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// A single data part. `id` matches between updates so the HUD
/// reconciles in-place. `transient` parts are dropped on
/// `DataPartBuffer::persistent_only` (after a cascade).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DataPart {
    /// Stable identifier — same id ⇒ update in-place on the client.
    pub id: String,
    /// Payload (raw text chunk, tool-call delta JSON, plan step
    /// snapshot, etc.). The HUD owns its own type discriminator on
    /// the client; here it's an opaque blob.
    pub payload: serde_json::Value,
    /// `true` when this part is partial (mid-stream, subject to
    /// rollback on cascade). `false` when it should survive the
    /// `persistent_only()` filter (final tool-call delta already
    /// journaled, plan diff, commit hash, etc.).
    pub is_transient: bool,
    /// Sequence number for HUD ordering — the HUD may render parts
    /// out-of-arrival-order when the WS link reorders, so it sorts
    /// by this field when displaying.
    pub seq: u64,
}

/// Reconciliation buffer maintained per mission (or per request when
/// no mission is active — the HUD cares about identity, not hierarchy). The orchestrator populates it as the model streams;
/// the HUD WS link consumes snapshots via `snapshot()`.
#[derive(Debug, Clone, Default)]
pub struct DataPartBuffer {
    parts: HashMap<String, DataPart>,
    next_seq: u64,
}

impl DataPartBuffer {
    pub fn new() -> Self {
        Self::default()
    }

    /// Insert or update a part. Same `id` ⇒ update in-place with the
    /// new payload (and the `seq` advances so the HUD knows it's
    /// newer). Returns the previous part, if any.
    pub fn upsert(
        &mut self,
        id: impl Into<String>,
        payload: serde_json::Value,
        is_transient: bool,
    ) -> Option<DataPart> {
        let id = id.into();
        let seq = self.next_seq;
        self.next_seq = self.next_seq.saturating_add(1);
        let part = DataPart {
            id,
            payload,
            is_transient,
            seq,
        };
        self.parts.insert(part.id.clone(), part)
    }

    /// Convenience: upsert a brand-new id generated by `Uuid::new_v4`.
    /// Useful for one-shot parts that don't need to be reconciled
    /// against an existing card.
    pub fn push(&mut self, payload: serde_json::Value, is_transient: bool) -> String {
        let id = Uuid::new_v4().to_string();
        self.upsert(&id, payload, is_transient);
        id
    }

    /// Fetch the part with the given id.
    pub fn get(&self, id: &str) -> Option<&DataPart> {
        self.parts.get(id)
    }

    /// Remove the part with the given id. Returns the removed part,
    /// if any.
    pub fn remove(&mut self, id: &str) -> Option<DataPart> {
        self.parts.remove(id)
    }

    /// Return the parts sorted by `seq`, suitable for serialisation
    /// to the HUD WS link.
    pub fn snapshot(&self) -> Vec<DataPart> {
        let mut parts: Vec<DataPart> = self.parts.values().cloned().collect();
        parts.sort_by_key(|p| p.seq);
        parts
    }

    /// Number of parts currently in the buffer.
    pub fn len(&self) -> usize {
        self.parts.len()
    }

    /// Is the buffer empty?
    pub fn is_empty(&self) -> bool {
        self.parts.is_empty()
    }

    /// Drop every transient part. Called by the orchestrator after a
    /// cascade resolves so the HUD only persists the durable deltas
    /// (tool-call results, plan diffs, commit messages) and forgets
    /// the primary's partial streaming frames. Returns the count of
    /// parts dropped so the journal can record the cascade event.
    pub fn persistent_only(&mut self) -> usize {
        let before = self.parts.len();
        self.parts.retain(|_, p| !p.is_transient);
        before - self.parts.len()
    }

    /// Clear the buffer entirely.
    pub fn clear(&mut self) {
        self.parts.clear();
        self.next_seq = 0;
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn upsert_inserts_new_part() {
        let mut buf = DataPartBuffer::new();
        let prev = buf.upsert("a", json!("hello"), true);
        assert!(prev.is_none());
        assert_eq!(buf.len(), 1);
        assert_eq!(buf.get("a").unwrap().payload, json!("hello"));
        assert!(buf.get("a").unwrap().is_transient);
    }

    #[test]
    fn upsert_same_id_updates_in_place() {
        let mut buf = DataPartBuffer::new();
        buf.upsert("a", json!("hello"), true);
        let prev = buf.upsert("a", json!("world"), false);
        assert_eq!(prev.unwrap().payload, json!("hello"));
        // The new payload is in place.
        assert_eq!(buf.get("a").unwrap().payload, json!("world"));
        assert!(!buf.get("a").unwrap().is_transient);
        // Seq advanced.
        assert!(buf.get("a").unwrap().seq > 0);
        assert_eq!(buf.len(), 1);
    }

    #[test]
    fn push_generates_unique_id() {
        let mut buf = DataPartBuffer::new();
        let id1 = buf.push(json!("a"), true);
        let id2 = buf.push(json!("b"), true);
        assert_ne!(id1, id2);
        assert_eq!(buf.len(), 2);
    }

    #[test]
    fn snapshot_sorted_by_seq() {
        let mut buf = DataPartBuffer::new();
        buf.upsert("a", json!(1), true);
        buf.upsert("b", json!(2), true);
        buf.upsert("c", json!(3), false);
        let snap = buf.snapshot();
        assert_eq!(snap.len(), 3);
        // Verify ascending seq.
        assert!(snap[0].seq < snap[1].seq);
        assert!(snap[1].seq < snap[2].seq);
        // Verify the ids correspond to insertion order.
        assert_eq!(snap[0].id, "a");
        assert_eq!(snap[1].id, "b");
        assert_eq!(snap[2].id, "c");
    }

    #[test]
    fn persistent_only_drops_transient_parts() {
        let mut buf = DataPartBuffer::new();
        buf.upsert("p1", json!("committed"), false);
        buf.upsert("t1", json!("streaming chunk 1"), true);
        buf.upsert("t2", json!("streaming chunk 2"), true);
        buf.upsert("p2", json!("tool result"), false);
        assert_eq!(buf.len(), 4);
        let dropped = buf.persistent_only();
        assert_eq!(dropped, 2);
        assert_eq!(buf.len(), 2);
        // The two persistent parts survive.
        assert!(buf.get("p1").is_some());
        assert!(buf.get("p2").is_some());
        // The transient parts are gone.
        assert!(buf.get("t1").is_none());
        assert!(buf.get("t2").is_none());
    }

    #[test]
    fn persistent_only_with_no_transient_returns_zero() {
        let mut buf = DataPartBuffer::new();
        buf.upsert("p1", json!("committed"), false);
        let dropped = buf.persistent_only();
        assert_eq!(dropped, 0);
    }

    #[test]
    fn clear_empties_and_resets_seq() {
        let mut buf = DataPartBuffer::new();
        buf.upsert("a", json!("x"), true);
        buf.upsert("b", json!("y"), true);
        assert!(!buf.is_empty());
        buf.clear();
        assert!(buf.is_empty());
        // After clear, next seq starts again at 0.
        buf.upsert("c", json!("z"), true);
        assert_eq!(buf.get("c").unwrap().seq, 0);
    }

    #[test]
    fn remove_returns_part() {
        let mut buf = DataPartBuffer::new();
        buf.upsert("a", json!("hello"), true);
        let removed = buf.remove("a");
        assert_eq!(removed.unwrap().payload, json!("hello"));
        assert!(buf.get("a").is_none());
        assert!(buf.is_empty());
    }

    #[test]
    fn remove_nonexistent_returns_none() {
        let mut buf = DataPartBuffer::new();
        assert!(buf.remove("ghost").is_none());
    }

    #[test]
    fn data_part_roundtrips_through_serde() {
        let p = DataPart {
            id: "abc".into(),
            payload: json!({"key": "value"}),
            is_transient: true,
            seq: 42,
        };
        let json = serde_json::to_string(&p).unwrap();
        let back: DataPart = serde_json::from_str(&json).unwrap();
        assert_eq!(p, back);
    }

    #[test]
    fn cascade_simulation_drops_partial_streaming_frames() {
        // Simulate a cascade: primary streams 4 chunks, then the
        // orchestrator re-dispatches to a fallback. The 4 chunks
        // are transient; a single tool-call delta is persistent
        // (already journaled). After persistent_only() the buffer
        // should only carry the journaled delta.
        let mut buf = DataPartBuffer::new();
        buf.upsert("stream_1", json!("Hel"), true);
        buf.upsert("stream_2", json!("lo, wor"), true);
        buf.upsert("stream_3", json!("ld"), true);
        buf.upsert("stream_4", json!("d!"), true);
        buf.upsert(
            "tool_call_diff",
            json!({"id": "toolu_1", "result": "ok"}),
            false,
        );
        assert_eq!(buf.len(), 5);
        let dropped = buf.persistent_only();
        assert_eq!(dropped, 4);
        assert_eq!(buf.len(), 1);
        assert!(buf.get("tool_call_diff").is_some());
    }
}
